sudo: required
services:
  - docker

before_install:
  - cd code/web/
  - docker build -t jessietabilisma/kaagapai-test .

script:
  - docker run jessietabilisma/kaagapai-test npm run test -- --coverage

deploy:
  provider: firebase
  on:
    branch: dev
  token:
    secure: "$Firebase_token"
