sudo: required
matrix:
  include:
  - language: node_js
    node_js: lts/*
    cache:
      directories:
      - node_modules
    before_install:
    - npm install -g firebase-tools
    - cd code/web/
    - npm install
    script:
    - npm test
    after_success:
    - travis_wait 40 npm run build
    - firebase use default --token $FIREBASE_TOKEN
    - travis_wait firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
    on:
      branch:
      - dev
      project: kaagapai-dev
  - language: node_js
    node_js: lts/*
    services: mysql
    cache:
      directories:
      - node_modules
    before_install:
    - cd code/api
    - npm install
    script: 'true'
    deploy:
      provider: heroku
      api_key:
        secure: sANRtabICC1qaEWbPUmr4XKF6dPPiYTBC1gzY9OkQ0JdLyl2La3z4cqNUXmjaMei5EmUVb6iBI1NCW41Ye8r4CFJJUQTTaRhQszmWtXzjDOgMDmyd64JzGADGnhEQ/SlTtFs0UIWOReq+aI7WbqjURYZMXvJFT+BFhWbs/kjtqsvLccVYkKFfEeQHgIbJWibKlj8YCOfUh5AOeLv50iw+BRa1EjJXOP9aMBHFTImQ35MwNOJ7XRbfcYyql/p0r/WgDFdOtOIvrkXhABIeKdeeOq8gfju+1u+Uc5BKNI5wfzNuRJnGPlzTDvdXLViQM1OhAWg3oVKsBRCp4QsN/HqHM5zNdDfCffeztE6ZDdXh/7r9N0YJwCmOc4IHXbyB1mcU8xMkg8dCb2iLOizmytl4s6yBGjx3HgXBR1hGeyYZvpNSMAFGYX8dJ3M97sxqxhBsd/YM7dU082sCuQ7PqSXIB3qw/oWGyicJPMKX7+xzYxVMhNBfNvMoewrORWoESCTG86umNLZlS3F4yG195jbOgUYST1EfYOPoaOoQ5O6MoSeAMImT1US0h6desFwXPalq/memmHIi6lxM9SzDIfZWwibqWagIqmIjSfJ4XpgNnBukKHfkxGHD/J/V9R3AM2lWKXRBSw7cu9TYoDxNVagcGKSEtjYNYhxnksVwVW3rkg=
      app:
        dev: kaagapai-dev
      on:
        repo: prometheus-tech/kaagapAI
        branches:
          only:
          - dev
notifications:
  email:
  - 2164149@slu.edu.ph
  - 2161495@slu.edu.ph
  - 2160809@slu.edu.ph
  - 2160120@slu.edu.ph
  - 2161745@slu.edu.ph
  - 2161436@slu.edu.ph
  - 2161794@slu.edu.ph